### ISSUE TITLE
Fail to create a project.

### ISSUE THREAD

**Issue by angelof-exe** [AvaloniaUI/AvaloniaVSCode#107]
### Describe the bug

When I try to create a new project it says "Failed to create project. Make sure you have Avalonia Project Templates installed." I already installed the Avalonia project templates with the command `dotnet new install Avalonia.Templates`

![Screenshot 2023-11-12 122941](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/47924499/2dfe22a6-74d5-4215-a1e4-9bafc837b7c4)

Windows 11
.NET 8.0

### To Reproduce

Create Avalonia Project

### Avalonia for VS Code

0.0.29

### VS Code version

1.86.1

### Relevant log output

```shell
N/A
```

**Comment by SignalMQ** [comment]
Hi, you not installed Avalonia.Templates yet.
Type to console:
`dotnet new install Avalonia.Templates`
and try again.
