### ISSUE TITLE
Create New item

### ISSUE THREAD

**Issue by henrrymoraes83** [AvaloniaUI/AvaloniaVSCode#116]
### Is your feature request related to a problem? Please describe.

This feature request is not related to a problem but a new ease and improvement

### Describe the solution you'd like

It will be very productive if you have a functionality to create a new Avalonia item,

New:
Resource Directory
Styles
TemplatedControl
User Control
Window

The example below is the Avalonia plugin for Visual Studio Community.

![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/137662373/3be6e15d-e41c-4fb6-a2e6-f8d758154609)

**Comment by prashantvc** [comment]
Duplicate of #38
