### ISSUE TITLE
VSCode: Project is created without sln but expects one

### ISSUE THREAD

**Issue by jojorne** [AvaloniaUI/AvaloniaVSCode#125]
### Describe the bug

If you do a `dotnet new avalonia.mvvm`, a new project will be created.
If you try to edit any axaml file, you'll get a `must build first` warming.
This warning never goes away! Upon a closer inspection, I noticed this:

```
[info] parser process args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"dotnet "~\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.29\solutionParserTool\SolutionParser.dll" "~\GetStartedApp\GetStartedApp.sln""
```

It calls for a **_SolutionParser_** which there is no sln file to parse.

By doing a `dotnet new sln` followed by `dotnet sln add` fixed the issue.

### To Reproduce

See above.

### Avalonia for VS Code

0.0.29

### Avalonia version

11.0.10

### VS Code version

1.90.1

### Relevant log output

```shell
See above.
```

**Comment by MrJul** [comment]
If no solution exists, SolutionParser falls back to listing .csproj files.
I've double checked that it works well without any solution after #146
