### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by RivenSkaye** [AvaloniaUI/AvaloniaVSCode#136]
The README still mentions not supporting anything newer than Avalonia 11.0.2, but it also hasn't been updated in almost a year. Meanwhile AvaloniaUI is up to 11.1.4 by now. What is the current supported version of Avalonia with this plugin?

**Comment by MrJul** [comment]
The plugin should really support any 11.x version, since Avalonia itself provides the preview (which is only an image displayed by the plugin).

I've tested it against 11.1.x and 11.2.x without any issues.
The warning is obsolete and will be removed by #147.
