### ISSUE TITLE
Document vsce as a development requirement

### ISSUE THREAD

**Issue by auxym** [AvaloniaUI/AvaloniaVSCode#139]
### Describe the bug

Sorry, I'm new to developing VS Code extensions :)

I read and followed the contribution guide, but failed to package the extension. Upon investigation, I found:

```
vsce: command not found
```

After running `npm install -g @vscode/vsce` I was able to successfully run the package task and create the VSIX file.

I would have created a PR for this, but I'm not sure if the vsce requirement should go in package.json, in build.sh (run the npm install command) or simply documented as a requirement in the contribution guide. If you let me know your preference I can submit a quick PR.

### To Reproduce

* Fresh install of vscode/npm/dotnet SDK
* Follow the contribution guide

### Avalonia for VS Code

master branch

### Avalonia version

NA

### VS Code version

1.95.3

### Relevant log output

```shell
Creating output directory: C:\Users\thef2102\source\AvaloniaVSCode/output/
Packaging extension to C:\Users\thef2102\source\AvaloniaVSCode/output/
C:\Users\thef2102\source\AvaloniaVSCode/.vscode/package.sh: line 23: vsce: command not found
 *  Terminal will be reused by tasks, press any key to close it.
```

**Comment by MikeCodesDotNET** [comment]
Fixed.
