### ISSUE TITLE
.NET Runtime 7.0.10 installation

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/AvaloniaVSCode#42]
I have .NET Runtime 7.0.10 available on my machine but this extension is still trying to download and install it, and eventually timeout. 
![image](https://github.com/AvaloniaUI/Avalonia-VSCode-Extension/assets/14807942/d4ae5b8f-ba25-460e-a2e5-9e7d5fd5459f)

**Comment by prashantvc** [comment]
VS Code will prompt you to set `dotnet` path now if it couldn't find one or it fails to download
