### ISSUE TITLE
Please publish this extension to the Open VSX

### ISSUE THREAD

**Issue by Dryadxon** [AvaloniaUI/AvaloniaVSCode#52]
Dear extension author, please publish this extension to the Open VSX marketplace.

Due to Microsoft's licensing restrictions, the majority of VS Code-derived products, such as [Gitpod](https://www.gitpod.io/), [Theia](https://theia-ide.org/)-based IDEs, and so forth, are unable to utilize Microsoft's Extensions Marketplace.

Therefore, it's important to also publish to [OpenVSX](https://open-vsx.org/), a vendor-neutral alternative to Microsoft's Extensions Marketplace, so that developers who use these versions of VS Code can find extensions like this one.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by prashantvc** [comment]
@MikeCodesDotNET  Open VSX supports VSCodium. We may want to publish the extension to Open VSX too

**Comment by prashantvc** [comment]
published
