### ISSUE TITLE
Feature Request: per profile installation

### ISSUE THREAD

**Issue by r9guy** [AvaloniaUI/AvaloniaVSCode#62]
Avalonia extension as of now doesn't support installation per VS Code profile, instead it installs to default profile.
One must apply extension to all profiles to have in .net workload.
in the picture below it's actually installed through .net profile, but after shuffling between default than back to .net it disappeared
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/9428627/decabdc2-d078-4372-b749-19ae91270dcd)

**Comment by ArcadeArchie** [comment]
It does work though? i've also installed it only in one profile but it doesnt disappear after shuffling thru other profiles(default profile included)

**Comment by r9guy** [comment]
> It does work though? i've also installed it only in one profile but it doesnt disappear after shuffling thru other profiles(default profile included)

you are right, this maybe was an issue related with vs code, which is fixed in 1.83.1
