### ISSUE TITLE
Building the preview is stuck in loading state

### ISSUE THREAD

**Issue by stefaandevylder** [AvaloniaUI/AvaloniaVSCode#65]
I'm unable to preview, it is stuck in building.
![image](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/10358801/4bd9e827-a314-458c-bd74-147b592a050c)

Using: VS Code Insiders, tried on version 0.0.22 & 0.0.21 both are a problem
My machine I'm using is: Lenovo IdeaPad Pro 5 16IRH8 83AQ004NMB Azerty
Windows installed.

**Comment by prashantvc** [comment]
I am sorry that you're hitting this issue. Could you try building the project manually `dotnet build` before the opening the preview?

I am going to check what's going on

**Comment by stefaandevylder** [comment]
Hi, yes, building via CMD works, but it does not fix the issue.

**Comment by Mrcubix** [comment]
Seems like upgrading to Avalonia 11.0.5 cause the issue.
It seems like this extension still uses version 11.0.4

**Comment by stefaandevylder** [comment]
So will there be another release for this?

**Comment by prashantvc** [comment]
Yes, I am working on the fix

**Comment by prashantvc** [comment]
I have fixed this issue, the changes are in the Avalonia library. It will take a while to get change go live.

For now the work around would be to use Avalonia v11.0.2 nuget package

**Comment by prashantvc** [comment]
Fixed in the version v0.0.24. Please verify, and reopen the bug if you continue to get the issue
