### ISSUE TITLE
AXAML intellisense in VS Code broken

### ISSUE THREAD

**Issue by tomschrot** [AvaloniaUI/AvaloniaVSCode#66]
Since update of Avalonia for VS Code (0.0.22) code completion in AXAML is no longer working.
Update to VS Code 1.84.0 won't fix. 
Downgrade to Avalonia to 0.0.21 doesn't fix.

**Comment by tomschrot** [comment]
It worked after update to 0.0.23! - very good

I just opend VSCode again and there was an update and I didn't notice what it was and now it's broken again! 😒

**Comment by prashantvc** [comment]
Fixed in v0.0.25
