### ISSUE TITLE
Previewer not working in Linux Mint

### ISSUE THREAD

**Issue by timamus** [AvaloniaUI/AvaloniaVSCode#67]
Previewer not working in Linux Mint. Version of extension is 0.0.23.

![Снимок экрана от 2023-11-11 10-40-58](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/48119843/92e79b5d-6e6b-468f-9f3b-ac5d50b461e7)

**Comment by prashantvc** [comment]
What version of Avalonia nuget package do you have in your project?

**Comment by timamus** [comment]
<PackageReference Include="Avalonia" Version="11.0.5" />

**Comment by timamus** [comment]
Previewer is working now in v0.0.24
