### ISSUE TITLE
Windows 11 Avalonia VSCode Extension almost dead

### ISSUE THREAD

**Issue by tomschrot** [AvaloniaUI/AvaloniaVSCode#69]
Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

After removing unused extensions & clean up 
(even reset of sync data on github)
un- and re-install of avalonia extension
XAML code completion and preview are not working
build target is .NET 7 
(The templates still address .NET 6, need update too! I'll be happy to take part in it.)

I use a well looked after custom settings file ( leave on request)
Maybe some settings are annoying?

**Comment by prashantvc** [comment]
Could you share more details? Can you elaborate what you mean be almost dead?

**Comment by tomschrot** [comment]
Oh sorry, sure:

even latest update (0.0.24)

no preview
no XAML Code completion
the project create seems to work
(though the templates need an update...)

I suspect that there could be side effects with other extensions...



![grafik](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/1196470/be7cda0e-bf9b-43fc-97ac-15647a66e569)

**Comment by prashantvc** [comment]
Can you share the `Avalonia Client` OUTPUT from the VS Code, please? I see the extension loaded correctly, it's interesting to see what's going on

**Comment by tomschrot** [comment]
Yes, I already captured it:
[Avalonia-Startup-Log.zip](https://github.com/AvaloniaUI/AvaloniaVSCode/files/13377578/Avalonia-Startup-Log.zip)

**Comment by tomschrot** [comment]
Maybe a list of the installed extensions may help?

Where are the Avalonia settings stored?

**Comment by Mrcubix** [comment]
No matter what is done, previews in 0.24.0 does not work anymore
```
2023-11-16 17:48:14.330 [info] Previewer assets generated at C:\Users\tinta\.nuget\packages\avalonia\11.0.4\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll
2023-11-16 17:48:14.331 [info] Command avalonia.previewProcess, file:///[...]/Touch-Gestures/Touch-Gestures.UX/Controls/GestureTile.axaml
2023-11-16 17:48:14.331 [info] Previewer assets are not available.
```
The 2 first lines seems normal, the third line seems weird, but was also present in 0.22.0

On the devtool side, the following warning now appear before the "[Extension Host] Congratulations, your extension "Avalonia UI" is now active!' line : 
```
[AXAML]: Invalid regular expression in `indentationRules.decreaseIndentPattern`:  SyntaxError: Invalid regular expression: /(</((?:([-_a-zA-Z0-9]+)(:))?([-_a-zA-Z0-9:]+))(>)/: Unterminated group
    at new RegExp (<anonymous>)
    at d.y (languageConfigurationExtensionPoint.ts:431:12)
    at d.z (languageConfigurationExtensionPoint.ts:462:38)
    at d.w (languageConfigurationExtensionPoint.ts:397:67)
    at d.h (languageConfigurationExtensionPoint.ts:129:9)
```

and this other warning appear after clicking the build button in the prompt provided by this extension : 
```
webviewElement.ts:512 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
```
Seems like an iframe is created but isn't shown to the user?

**Comment by Mrcubix** [comment]
> Could you share the output from `dotnet --list-sdks`? I believe this due to dotnet 8 changes

```
3.1.426 [c:\program files\dotnet\sdk]
5.0.408 [c:\program files\dotnet\sdk]
6.0.417 [c:\program files\dotnet\sdk]
7.0.114 [c:\program files\dotnet\sdk]
7.0.404 [c:\program files\dotnet\sdk]
```

**Comment by prashantvc** [comment]
Could you try the latest version of the extension and confirm this is still an issue?
it should be fixed now, please make sure you have .NET core 8 installed

**Comment by Mrcubix** [comment]
> it should be fixed now

Nothing has changed, the result is the same, with and without using .NET 8, Avalonia 11.0.5, 6 & 7
