### ISSUE TITLE
Previewer is not working when axaml is inside subfolder

### ISSUE THREAD

**Issue by LtDetFrankDrebin** [AvaloniaUI/AvaloniaVSCode#70]
Previewer for default "MainWindow.axaml" from "avalonia.mvvm" template does not work until I move "MainWindow.axaml" from "./Views" subfolder to project's root folder. (Ubuntu)

**Comment by PedroSaraviaQ** [comment]
Same, it doesn't seem to work when the files are in subfolders.

**Comment by prashantvc** [comment]
Could you share the output from `dotnet --list-sdks`? I believe this due to dotnet 8 changes

**Comment by LtDetFrankDrebin** [comment]
dotnet --list-sdks
6.0.125 [/usr/lib/dotnet/sdk]
7.0.114 [/usr/lib/dotnet/sdk]

**Comment by prashantvc** [comment]
You need dotnet v8 for extension to function. Could you give it another try and reopen the issue if you continue see the issue
