### ISSUE TITLE
Preview not available even if built

### ISSUE THREAD

**Issue by arkoste** [AvaloniaUI/AvaloniaVSCode#82]
Type: <b>Bug</b>

Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Avalonia Extention v0.0.25

After creation of example project with "dotnet new avalonia.app -o MyApp" i've rebuilt the project but no preview or intellisense is available. 

If i click on Show Preview i receive the message "Previewer is not available. Build the project first." ... but build is already present

What i did wrong?

Extension version: 0.0.25
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (18.64GB free)|
|Process Argv|--folder-uri file:///d%3A/Progetti_DOTNET/varie/Avalonia/AvaloniaVsCode2 --crash-reporter-id fa9b17c6-d7c7-4d6c-84af-d30f2c7db0c3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by BinToss** [comment]
Which version of Avalonia does your project reference? Anything past 11.0.5 is not yet supported due to some minor breaking changes in that version.

**Comment by arkoste** [comment]
11.0.6

**Comment by maxkatz6** [comment]
> Anything past 11.0.5 is not yet supported due to some minor breaking changes in that version.

What are you referring to? Which breaking change?

**Comment by BinToss** [comment]
https://github.com/AvaloniaUI/AvaloniaVSCode#requires-avalonia-v1102-or-lower
> The extension require Avalonia nuget package v11.0.2 or lower. **The latest version v11.0.5 of Avalonia package will break the previewer**

**Comment by victorem1** [comment]
I've encountered the same issue. Changing project references from 
`<PackageReference Include="Avalonia" Version="11.0.10" />` to `<PackageReference Include="Avalonia" Version="11.0.2" />` etc. didn't help, and per `dotnet new avalonia.app -o AvaloniaTest --help` the only version options are 
`  -av, --avalonia-version <choice>  The target version of Avalonia NuGet packages.
                                    Type: choice
                                      11.0.10       Target 11.0.10 (Latest stable)
                                      11.1.0-beta1  Target 11.1.0-beta1 (Next version)
                                    Default: 11.0.10
`. 

How can one create a project with 11.0.2?
