### ISSUE TITLE
AvaloniaVSCode is stale on OpenVSX at version 0.0.20

### ISSUE THREAD

**Issue by Shoun2137** [AvaloniaUI/AvaloniaVSCode#85]
### Is your feature request related to a problem? Please describe.

Yes, I've had a previewer problem on my leenooks VSCodium, it was stuck at grayed out "Build preview" button!

### Describe the solution you'd like

Please upload fresh VSIX files at OpenVSX!

### Describe alternatives you've considered

Of course, I've downloaded the files from github releases, and that fixed the previewer problem, but it's a hassle ;f

### Additional context

❤️

**Comment by prashantvc** [comment]
Published the new version to Open VSX

**Comment by nkonidaris** [comment]
Good day, @prashantvc 
Could I bother you to update the [Open VSX repository version ](https://open-vsx.org/extension/AvaloniaTeam/vscode-avalonia)of the VScode extension to match MS VScode Marketplace ? 

Side note: There is a warning about namespaces with a link to the following documentation that might be of interest.
https://github.com/eclipse/openvsx/wiki/Namespace-Access
