### ISSUE TITLE
Previewer is not available. Build the project first. Not working

### ISSUE THREAD

**Issue by dire64** [AvaloniaUI/AvaloniaVSCode#88]
### Describe the bug

I am trying to develop a project using Avalonia on macOS I am on macOS 14.2.1 and VSCode but when I try to open the previewer it says "Previewer is not available. Build the project first." I click build but it seems like nothing is happening. I can click it as many times as I want and nothing happens.

I read the readme on here and noticed it says 11.0.5 causes previewer issues, I am on version 11.0.6. I am not sure how to downgrade it until this matter is resolved.

### To Reproduce

Create a new Avalonia project
Try to open the previewer
When prompted to build click build
Nothing happens

### Avalonia for VS Code

0.0.26

### Avalonia version

11.0.6

### VS Code version

1.85.1

### Relevant log output

```shell
AvaloniaTeam.vscode-avalonia requested to download the .NET Runtime.
AvaloniaTeam.vscode-avalonia wants to install .NET 8.0.1~arm64 but it already exists. No downloads or changes were made.
```

**Comment by ai25395** [comment]
Same bug for me.

**Comment by prashantvc** [comment]
Thanks for reporting the bug I am actively working on fixing this :)

**Comment by prashantvc** [comment]
Could you try using the v0.0.29 version? https://github.com/AvaloniaUI/AvaloniaVSCode/releases/tag/v0.0.29

**Comment by trampster** [comment]
v0.0.29 fixes it for me on linux

**Comment by prashantvc** [comment]
@dire64 could you confirm v0.0.29 fixes it for you too?

**Comment by michaeljon** [comment]
Not working here. Same symptom - need build, click build, prompted to build again.

**Comment by prashantvc** [comment]
@michaeljon Could you share the steps to reproduce?

**Comment by dire64** [comment]
Can confirm that it is fixed!

**Comment by prashantvc** [comment]
Closing this. Please comment if you want me to reopen it

**Comment by ScruffyDerHausmeister** [comment]
I still have the bug in v0.0.31 on linux.

**Comment by DirectorRen-TV** [comment]
I faced it too in v0.0.31 on windows 10

`dotnet build .\GetStartedApp.csproj` didn't fixed it, extension still wanting to build before previewing

**Comment by l0hn** [comment]
I have the same bug on macOS.

**Comment by trampster** [comment]
Please reopen, I still have this bug on Ubuntu 22.04 v0.0.31

**Comment by fgimian** [comment]
Same issue here on Windows with the latest .NET, VS Code and related extension.

**Comment by trampster** [comment]
I asked about this on x. 

This is the answer I got from Mike James was:

> We prioritised shipping the core functionality and have since opened it to the community contributions.
> We encourage users who want specific improvements or fixes to get involved and contribute.

It seems that Avalonia are not going to fix/maintain this extension going forward. And are looking for the community to do it.

I would be willing to try fixing this, but I can't find any instructions/guides about how to get setup for debugging/developing the extension.

I asked for help on X but I did not get a response.

**Comment by toolateralus** [comment]
yep same issue on linux mint (ubuntu 22.04 I think)

**Comment by 1ogix** [comment]
had the same issue on my macOS

**Comment by prashantvc** [comment]
I will take a look at this later this weekend, if you have steps to reproduce, please leave a comment

**Comment by trampster** [comment]
@prashantvc I don't know of a set of steps that make it work.

**Comment by JBrolin90** [comment]
Now I tried on Windows 11, Linux Mint Debian edition 6 (on 2 machines) All with the same result, does not load the previewer. Additionally I tried with several earlier versions 0.31 and down to 0.25. All with the same result. I would therefore assume that the problem lies in some change in VS Code itself, not the extension. I did not try to downgrade VS Code

**Comment by super-brian** [comment]
on Mac, using .net 8 sdk, vs code, Avalonia for VSCode 0.0.31, the first app did work (MyApp) the GetStartedApp doesn't work.

**Comment by Advanium** [comment]
I got it working for v0.0.31 on my Windows machine with latest .NET 8.0 SDK installed by swapping out the SolutionParser files:

See https://github.com/AvaloniaUI/AvaloniaVSCode/issues/40#issuecomment-2500042642

**Comment by marcin-przywoski** [comment]
This won't work if you have .NET 9 installed. Check the comment above if you do but compile the project with .NET 9 - then it will start working.

**Comment by ScruffyDerHausmeister** [comment]
Will be there any bugfix?

**Comment by wallacemaxters** [comment]
Same problem in Linux mint, with 0.0.31 or 0.0.29 version of plugin.

**Comment by hyaterreka** [comment]
Issue still exists with both 0.0.31/0.0.29. Makes the extension completely useless. Running on windows 10.

**Comment by Knar33** [comment]
I am having this issue in Ubuntu 24.04.2 using 0.32

**Comment by DIMANRUS** [comment]
I am having this issue in Windows 11, version 0.0.32, .NET 9

![Image](https://github.com/user-attachments/assets/25263160-3761-4360-8828-30af194004c7)

**Comment by OptimusPi** [comment]
![Image](https://github.com/user-attachments/assets/0590d930-915c-499d-bd71-3afb93b76d64)

Same issue for me with net8.0 or net9.0 target

**Comment by Sjshi763** [comment]
> ![Image](https://github.com/user-attachments/assets/0590d930-915c-499d-bd71-3afb93b76d64)
> 
> Same issue for me with net8.0 or net9.0 target


I asked them, this issue is a low priority for them, and the repair is up to us

**Comment by jedomed** [comment]
Same issue in both VS Code and VS Codium. How is this low priority? ☹️ I just discovered Avalonia, wanted to see if it's a good alternative to Qt, and on page 3 of Get Started and I'm already hitting a wall.

**Comment by jedomed** [comment]
> Because ,them using Rider(IDE).And I try Rider + Avalonia It working.

It's OK if their priority is on Rider and VS Code is secondary, but if that's the case I think they should make it clearer on the website. Add a note saying that the VS Code extension is still work-in-progress or something... that way people won't assume that it's polished and waste their time trying to set it up.

**Comment by Sjshi763** [comment]
> > Because ,them using Rider(IDE).And I try Rider + Avalonia It working.
> 
> It's OK if their priority is on Rider and VS Code is secondary, but if that's the case I think they should make it clearer on the website. Add a note saying that the VS Code extension is still work-in-progress or something... that way people won't assume that it's polished and waste their time trying to set it up.

To be honest, it's quite stretched

**Comment by forti-xd** [comment]
I've tried everything. the error still exists. I tried net8.0, net9.0, net10.0. Rolled back to avalonia for vscode v0.0.29. nothing helped.

<img width="460" height="96" alt="Image" src="https://github.com/user-attachments/assets/c82330b9-0a8f-4f47-8916-9d330f353483" />
