### ISSUE TITLE
[Feature] Change vscode-avalonia SolutionParser, avaloniaServer platform target to .NET Standard 2.0

### ISSUE THREAD

**Issue by SignalMQ** [AvaloniaUI/AvaloniaVSCode#90]
### Is your feature request related to a problem? Please describe.

Is it possible to change the target platform for `vscode-avalonia` to `.NET standard 2.0` so that it is supported simultaneously in SDK versions like `6.0, 7.0, 8.0`?

### Describe the solution you'd like

no response

### Describe alternatives you've considered

no response

### Additional context

no response

**Comment by prashantvc** [comment]
MSBuild tools will not work when I targeted to .NET standard 2.0
Unfortunately I cannot fix take this up for now

**Comment by MrJul** [comment]
This isn't possible: the SolutionParser needs to locate and load the appropriate MSBuild assemblies, which target a specific .NET version.
